dataset<-read.csv("NewsPopularity.csv")
View(dataset)
newdataset<-dataset[complete.cases(dataset), ]
str(newdataset)
newdataset<-na.omit(dataset)
summary(newdataset)
size <- floor(0.80 * nrow(newdataset))
set.seed(101)
train_ind <- sample(seq_len(nrow(newdataset)),size = size)
train <- newdataset[train_ind, ]
test <- newdataset[-train_ind, ]
pcacalc <- prcomp(test[ ,2:60],center =TRUE,scale. = TRUE)
print(pcacalc)
plot(pcacalc,type = "l")
summary(pcacalc)
install.packages("devtools")
library("devtools", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
install_github("ggbiplot", "vqv")
library(ggbiplot)
biplotpca<-ggbiplot(pcacalc,obs.scale = 1,var.scale = 1, groups =NULL,ellipse =TRUE,circle = TRUE)
biplotpca<-biplotpca+scale_color_discrete(name ='')
biplotpca<-biplotpca+theme(legend.direction = 'horizontal', legend.position ='top')
print(biplotpca)
biplotpca2<-biplot(pcacalc)
